// scripts/generate-assets.mjs
// Rasterizes the First Light brand SVGs into the PNGs the site needs:
//   - src/app/apple-icon.png   (180×180 apple-touch icon)
//   - public/favicon-32.png    (32×32 legacy favicon)
//   - public/icon-512.png      (512×512, used by the web manifest)
//   - src/app/opengraph-image.png (1200×630 social share card)
//
// Run whenever the logo, the tagline in src/config/links.ts, or the brand
// colors change:  npm run gen:assets
//
// The OG card is a generated PNG that no copy or CSS change touches, so it
// has to be regenerated by hand or it keeps serving stale artwork to every
// LinkedIn, Slack and iMessage link preview.
//
// Icons render from brand/favicon.svg (the First Light tile). The OG card
// embeds the signature logo as outlined paths (no font needed) and sets the
// tagline in Instrument Sans from scripts/fonts/ through a private fontconfig
// file, so the card renders the same on any machine.

import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// Point fontconfig (used by sharp's SVG renderer) at the bundled Instrument
// Sans before sharp loads, so the tagline never falls back to a system face.
const fontsDir = join(__dirname, "fonts");
const fontsConf = join(tmpdir(), "steinproduct-fonts.conf");
writeFileSync(
  fontsConf,
  `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>${fontsDir}</dir>
  <cachedir>${join(tmpdir(), "steinproduct-fontconfig-cache")}</cachedir>
</fontconfig>
`,
);
process.env.FONTCONFIG_FILE = fontsConf;
const sharp = (await import("sharp")).default;

// First Light, Night (must match src/app/globals.css tokens).
const VOID = "#050C0E";
const SURFACE_1 = "#0A1719";
const STEIN_TEAL = "#0E6B6B";
const AURORA = "#34F5C5";
const ORBIT = "#5CD6FF";
const INK = "#E8FBF6";
const INK_MUTED = "#9CB9B4";

// The tagline is the one string that feeds the footer, the manifest and this
// card. Read it from the source of truth instead of retyping it.
const linksSource = readFileSync(join(root, "src", "config", "links.ts"), "utf8");
const TAGLINE = linksSource.match(/tagline:\s*"([^"]+)"/)?.[1];
if (!TAGLINE) throw new Error("Could not read SITE.tagline from src/config/links.ts");

const faviconSvg = readFileSync(join(root, "brand", "favicon.svg"));

async function pngFromSvg(svgBuffer, size, outPath) {
  await sharp(svgBuffer, { density: 384 })
    .resize(size, size, { fit: "contain" })
    .png()
    .toFile(outPath);
  console.log("✓", outPath.replace(root + "/", ""));
}

// --- Icons (the First Light tile) ---
mkdirSync(join(root, "public"), { recursive: true });
await pngFromSvg(faviconSvg, 180, join(root, "src", "app", "apple-icon.png"));
await pngFromSvg(faviconSvg, 32, join(root, "public", "favicon-32.png"));
await pngFromSvg(faviconSvg, 512, join(root, "public", "icon-512.png"));

// --- Open Graph card (1200×630) ---
const W = 1200;
const H = 630;

// The signature logo as outlined paths, embedded as a nested <svg>. Strip any
// metadata and the outer element; keep its defs, masks and paths verbatim.
const signatureFile = readFileSync(
  join(root, "brand", "first-light", "logos", "stein-signature-night.svg"),
  "utf8",
);
const signatureViewBox = signatureFile.match(/viewBox="([^"]+)"/)[1];
const [, , vbW, vbH] = signatureViewBox.split(/\s+/).map(Number);
const signatureInner = signatureFile
  .replace(/<metadata>[\s\S]*?<\/metadata>/, "")
  .replace(/^[\s\S]*?<svg[^>]*>/, "")
  .replace(/<\/svg>\s*$/, "");
const SIG_W = 640;
const SIG_H = Math.round((SIG_W * vbH) / vbW);
const SIG_X = (W - SIG_W) / 2;
const SIG_Y = 132;

// The planet limb: a huge circle whose top edge crosses the lower third,
// filled with void below and glowing aurora along the rim.
const LIMB_R = 1400;
const LIMB_TOP = 520;
const LIMB_CY = LIMB_TOP + LIMB_R;

const ogSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <defs>
    <radialGradient id="atmosphere" gradientUnits="userSpaceOnUse" cx="600" cy="693" r="760"
      gradientTransform="translate(600 693) scale(1 0.58) translate(-600 -693)">
      <stop offset="0" stop-color="${STEIN_TEAL}"/>
      <stop offset="0.48" stop-color="${SURFACE_1}"/>
      <stop offset="0.78" stop-color="${VOID}"/>
    </radialGradient>
    <pattern id="stars" width="32" height="32" patternUnits="userSpaceOnUse">
      <circle cx="1" cy="1" r="1" fill="${INK}" opacity="0.18"/>
    </pattern>
    <radialGradient id="starfade" cx="0.5" cy="0.3" r="0.7">
      <stop offset="0.2" stop-color="#fff" stop-opacity="1"/>
      <stop offset="0.75" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>
    <mask id="starmask"><rect width="${W}" height="${H}" fill="url(#starfade)"/></mask>
    <filter id="glow-soft" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="14"/>
    </filter>
    <filter id="glow-wide" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="48"/>
    </filter>
  </defs>

  <rect width="${W}" height="${H}" fill="${VOID}"/>
  <rect width="${W}" height="${H}" fill="url(#atmosphere)"/>
  <rect width="${W}" height="${H}" fill="url(#stars)" mask="url(#starmask)"/>

  <!-- planet limb glow, then the crisp rim, then the planet body in void -->
  <circle cx="600" cy="${LIMB_CY}" r="${LIMB_R}" fill="none" stroke="${ORBIT}" stroke-opacity="0.35" stroke-width="60" filter="url(#glow-wide)"/>
  <circle cx="600" cy="${LIMB_CY}" r="${LIMB_R}" fill="none" stroke="${AURORA}" stroke-opacity="0.6" stroke-width="18" filter="url(#glow-soft)"/>
  <circle cx="600" cy="${LIMB_CY}" r="${LIMB_R}" fill="${VOID}"/>
  <circle cx="600" cy="${LIMB_CY}" r="${LIMB_R}" fill="none" stroke="${AURORA}" stroke-opacity="0.9" stroke-width="3"/>

  <!-- the signature logo, outlined paths from brand/first-light/logos -->
  <svg x="${SIG_X}" y="${SIG_Y}" width="${SIG_W}" height="${SIG_H}" viewBox="${signatureViewBox}" overflow="visible">
    ${signatureInner}
  </svg>

  <!-- tagline and domain, centered under the signature -->
  <text x="${W / 2}" y="${SIG_Y + SIG_H + 56}" text-anchor="middle" font-family="Instrument Sans" font-size="34" font-weight="400" fill="${INK_MUTED}">${TAGLINE}</text>
  <text x="${W / 2}" y="${SIG_Y + SIG_H + 104}" text-anchor="middle" font-family="Instrument Sans" font-size="21" font-weight="500" letter-spacing="3" fill="${AURORA}">steinproduct.com</text>
</svg>`;

await sharp(Buffer.from(ogSvg), { density: 144 })
  .png()
  .toFile(join(root, "src", "app", "opengraph-image.png"));
console.log("✓", "src/app/opengraph-image.png");
